[package]
name = "dummy_data_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
rand = { version = "0.8", features = ["small_rng"] }
csv = "1"
encoding_rs = "0.8"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
chrono = "0.4"
rayon = "1"
serde_json = { version = "1", features = ["preserve_order"] }
uuid = "1"
indicatif = "0.17"
rust_xlsxwriter = "0.79"

[dev-dependencies]
calamine = "0.26"
